# Generated by Django 3.2.8 on 2021-10-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addres',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.PositiveIntegerField(null=True, verbose_name='کدپستی'),
        ),
    ]
