# Generated by Django 3.2.8 on 2021-12-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211102_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('f', 'تحویل شده'), ('s', 'ثبت شده'), ('e', 'در حال ارسال'), ('b', 'در حال بررسی')], max_length=50, null=True, verbose_name='وضعیت سفارش'),
        ),
    ]
